version: '3.9'
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: e-commerce
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-app:
    build: ./   # đường dẫn tới Dockerfile của bạn
    container_name: spring-app
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/e-commerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"

volumes:
  pgdata:
